from contextlib import asynccontextmanager

from fastapi import FastAPI, Depends, Body
from app.auth import get_current_user
from app.models import User

from fastapi.middleware.cors import CORSMiddleware

from fastmcp.server.openapi import OpenAPITool
import httpx
from fastmcp.server.openapi import RouteMap, RouteType
import jsonref

import base64

from anthropic import Anthropic
from fastapi import Body

import json
from mcp.types import TextContent
from fastmcp.server.openapi import FastMCPOpenAPI

from fastmcp import FastMCP
from mcp.server.sse import SseServerTransport
from starlette.requests import Request

from app.config import settings
from app.db import create_db_and_tables
from app.enums import ACTIVITY_BY_CATEGORY, CraCategory, ExpenseType, Status
from app.routers import auth as auth_router
from app.routers import cra as cra_router
from app.routers import cra_tracking as cra_tracking_router
from app.routers import expenses as expenses_router
from app.seed import seed_demo_data


@asynccontextmanager
async def lifespan(app: FastAPI):
    create_db_and_tables()
    seed_demo_data()
    yield


app = FastAPI(
    title='CRA Mock API',
    version='0.1.0',
    description='Simplified mock backend for CRA / Expenses / CRA Tracking pages.',
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=True,
    allow_methods=['*'],
    allow_headers=['*'],
)

app.include_router(auth_router.router, prefix='/api/auth', tags=['auth'])
app.include_router(cra_router.router, prefix='/api/cra', tags=['cra'])
app.include_router(cra_tracking_router.router, prefix='/api/cra-tracking', tags=['cra-tracking'])
app.include_router(expenses_router.router, prefix='/api/expenses', tags=['expenses'])


@app.get('/healthz', tags=['meta'])
def healthz() -> dict:
    return {'status': 'ok'}


@app.get('/api/enums', tags=['meta'])
def get_enums() -> dict:
    return {
        'cra_categories': [c.value for c in CraCategory],
        'cra_activities': {
            cat.value: [a.value for a in acts] for cat, acts in ACTIVITY_BY_CATEGORY.items()
        },
        'expense_types': [t.value for t in ExpenseType],
        'statuses': [s.value for s in Status],
    }




# Token storage — cannot use a simple variable in async, dict content can be modified
_token = {"value": ""}


class DynamicAuthTransport(httpx.AsyncBaseTransport):
    """
    Custom HTTP transport that injects the JWT token automatically into every request.
    Wraps httpx.ASGITransport to intercept requests before they reach the FastAPI app.
    Without this, all tools generated by from_openapi would return 401 Unauthorized.
    """
    def __init__(self, app):
        """Wrap the FastAPI ASGI app so requests go directly without network."""
        self._transport = httpx.ASGITransport(app=app)

    async def handle_async_request(self, request):
        """Intercept every request and inject the Bearer token if one is stored."""
        if _token["value"]:
            request.headers["Authorization"] = f"Bearer {_token['value']}"
        return await self._transport.handle_async_request(request)


# Patch OpenAPITool to wrap results in TextContent
original_execute = OpenAPITool._execute_request

async def patched_execute_request(self, *args, **kwargs):
    """
    Patch for OpenAPITool._execute_request.
    By default, tools return raw dict or list — MCP expects TextContent format.
    This patch converts dict/list results to JSON string to fix 208 validation errors.
    Must be applied before creating the MCP server with from_openapi.
    """
    result = await original_execute(self, *args, **kwargs)
    if isinstance(result, (dict, list)):
        return json.dumps(result)
    return result

OpenAPITool._execute_request = patched_execute_request


# All tools use this client — token injected automatically
http_client = httpx.AsyncClient(
    transport=DynamicAuthTransport(app),
    base_url="http://fastapi"
)


# Auto-generate all tools from FastAPI OpenAPI spec
# jsonref resolves $ref, exclude_operations removes auto-generated login
# route_maps forces GET routes to be tools instead of resources
mcp = FastMCP.from_openapi(
    openapi_spec=jsonref.replace_refs(app.openapi()),
    client=http_client,
    exclude_operations=["login_api_auth_login_post"],
    route_maps=[
        RouteMap(methods=["GET", "POST", "PUT", "DELETE"], pattern=".*", route_type=RouteType.TOOL)
    ]
)


@mcp.tool()
async def login(email: str, password: str) -> str:
    """
    Login to Portalite and get JWT token. Always call this first.
    from_openapi does not support OAuth2 form data — this tool sends the correct
    form data format and stores the token so DynamicAuthTransport injects it
    automatically into all subsequent requests.
    """
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app),
        base_url="http://fastapi"
    ) as client:
        resp = await client.post(
            "/api/auth/login",
            data={"username": email, "password": password}
        )
        result = resp.json()
        _token["value"] = result["access_token"]
        return json.dumps(result)


@mcp.tool()
async def create_expense_with_receipt(
    expense_type: str,
    month: str,
    total_amount: float,
    description: str,
    image_base64: str,
    image_mime_type: str = "image/jpeg",
    billable_to_client: bool = False,
    comment: str = ""
) -> str:
    """
    Create an expense report with a receipt image sent by the user in the conversation.
    When the user uploads or pastes an image (ticket, receipt, invoice), automatically:
    1. Read the image from the conversation
    2. Encode it to base64
    3. Call this tool with the base64 data

    DO NOT ask the user to encode the image manually.
    DO NOT use file paths.
    expense_type: Restaurant, Titre de transport, Materiel, Telephonie, Teletravail, Autre.
    month: YYYY-MM format.
    image_base64: encode the image from the conversation to base64 and pass it here.
    image_mime_type: image/jpeg, image/png or application/pdf.
    """
    try:
        image_bytes = base64.b64decode(image_base64)
        ext = image_mime_type.split("/")[-1]
        filename = f"receipt.{ext}"
        async with httpx.AsyncClient(
            transport=httpx.ASGITransport(app=app),
            base_url="http://fastapi",
            headers={"Authorization": f"Bearer {_token['value']}"}
        ) as client:
            resp = await client.post(
                "/api/expenses",
                data={
                    "type": expense_type,
                    "month": month,
                    "total_amount": str(total_amount),
                    "description": description,
                    "billable_to_client": str(billable_to_client).lower(),
                    "comment": comment
                },
                files={"receipt": (filename, image_bytes, image_mime_type)}
            )
            return json.dumps(resp.json())
    except Exception as e:
        return json.dumps({"error": str(e)})


@mcp.tool()
async def extract_expense(
    image_base64: str,
    month: str,
    image_mime_type: str = "image/jpeg"
) -> str:
    """
    Extract expense data from a receipt image and create the expense automatically.
    When the user sends a ticket or receipt image in the conversation:
    1. Encode the image to base64
    2. Call this tool — it uses Claude Vision to extract the data
    3. Then creates the expense with the receipt attached
    DO NOT ask the user for the data manually — extract it from the image.
    image_base64: the image from the conversation encoded in base64.
    month: YYYY-MM format.
    """
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app),
        base_url="http://fastapi",
        headers={"Authorization": f"Bearer {_token['value']}"}
    ) as client:
        resp = await client.post(
            "/api/extract-expense",
            json={
                "image_base64": image_base64,
                "image_mime_type": image_mime_type,
                "month": month
            }
        )
        return json.dumps(resp.json())


anthropic_client = Anthropic()

@app.post("/api/extract-expense", tags=["meta"])
async def extract_expense(
    payload: dict = Body(...),
    current: User = Depends(get_current_user)
):
    """Extract expense data from a receipt image using Claude Vision and create the expense."""
    image_base64 = payload.get("image_base64")
    image_mime_type = payload.get("image_mime_type", "image/jpeg")
    month = payload.get("month")

    # Call Claude Vision to extract data
    response = anthropic_client.messages.create(
        model="claude-opus-4-5",
        max_tokens=500,
        messages=[{
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": image_mime_type,
                        "data": image_base64
                    }
                },
                {
                    "type": "text",
                    "text": "Extrait les données de ce ticket de caisse. Retourne UNIQUEMENT un JSON avec: type (Restaurant/Titre de transport/Materiel/Telephonie/Teletravail/Autre), total_amount (float), description (string), comment (string)."
                }
            ]
        }]
    )

    import re
    text = response.content[0].text
    match = re.search(r'\{.*\}', text, re.DOTALL)
    data = json.loads(match.group())

    return {
        "extracted": data,
        "month": month
    }


# Rename tool that exceeds 64 characters limit required by Claude Desktop
mcp._tool_manager._tools["import_client_cra"] = mcp._tool_manager._tools.pop("import_client_cra_api_cra_tracking_months__month__import_client_cra_post")

# Mount MCP on FastAPI via SSE
app.mount("/mcp", mcp.sse_app())